/*
 * Mirror Twins — level data. GENERATED by generate.js — do not edit by hand.
 * 50 levels across 5 chapters; every one is BFS-verified solvable.
 * Regenerate with: node generate.js   (then: node verify.js)
 */

var CHAPTERS = [
  {
    "name": "First Steps",
    "blurb": "Guide each twin onto its own matching ring."
  },
  {
    "name": "Reflections",
    "blurb": "Mirror twins flip your moves — watch which way each one goes."
  },
  {
    "name": "Blocking Walls",
    "blurb": "Walls stop one twin while the others keep moving. Use them."
  },
  {
    "name": "Spikes",
    "blurb": "Spikes reset the level. Route every twin safely around them."
  },
  {
    "name": "Mastery",
    "blurb": "Everything at once: mirrors, rotations, walls and spikes."
  }
];

var LEVELS = [
  {
    name: "First Steps 1", chapter: 0, moves: 3,
    hint: "Guide each twin onto its own matching ring.",
    w: 4, h: 5, walls: [], hazards: [],
    avatars: [
      { start: [3,0], goal: [3,3], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 2", chapter: 0, moves: 3,
    hint: "Guide each twin onto its own matching ring.",
    w: 4, h: 4, walls: [], hazards: [],
    avatars: [
      { start: [0,0], goal: [1,2], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 3", chapter: 0, moves: 3,
    hint: "Guide each twin onto its own matching ring.",
    w: 4, h: 4, walls: [], hazards: [],
    avatars: [
      { start: [2,2], goal: [0,1], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 4", chapter: 0, moves: 3,
    hint: "Guide each twin onto its own matching ring.",
    w: 4, h: 4, walls: [], hazards: [],
    avatars: [
      { start: [0,2], goal: [1,0], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 5", chapter: 0, moves: 4,
    hint: "Guide each twin onto its own matching ring.",
    w: 5, h: 5, walls: [], hazards: [],
    avatars: [
      { start: [0,1], goal: [4,1], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 6", chapter: 0, moves: 4,
    hint: "Guide each twin onto its own matching ring.",
    w: 5, h: 4, walls: [], hazards: [],
    avatars: [
      { start: [0,0], goal: [2,2], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 7", chapter: 0, moves: 4,
    hint: "Guide each twin onto its own matching ring.",
    w: 5, h: 5, walls: [], hazards: [],
    avatars: [
      { start: [2,0], goal: [2,4], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 8", chapter: 0, moves: 4,
    hint: "Guide each twin onto its own matching ring.",
    w: 5, h: 5, walls: [], hazards: [],
    avatars: [
      { start: [0,3], goal: [3,2], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 9", chapter: 0, moves: 4,
    hint: "Guide each twin onto its own matching ring.",
    w: 4, h: 4, walls: [], hazards: [],
    avatars: [
      { start: [1,0], goal: [3,2], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "First Steps 10", chapter: 0, moves: 6,
    hint: "Guide each twin onto its own matching ring.",
    w: 4, h: 5, walls: [], hazards: [],
    avatars: [
      { start: [3,3], goal: [0,0], color: "#22d3ee", transform: "normal" },
    ],
  },
  {
    name: "Reflections 1", chapter: 1, moves: 6,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[2,1]], hazards: [],
    avatars: [
      { start: [4,0], goal: [0,2], color: "#22d3ee", transform: "normal" },
      { start: [5,0], goal: [1,0], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Reflections 2", chapter: 1, moves: 8,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[2,0]], hazards: [],
    avatars: [
      { start: [1,4], goal: [2,2], color: "#22d3ee", transform: "mirrorX" },
      { start: [5,1], goal: [1,0], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Reflections 3", chapter: 1, moves: 9,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[0,0], [0,3]], hazards: [],
    avatars: [
      { start: [4,2], goal: [2,2], color: "#22d3ee", transform: "normal" },
      { start: [1,3], goal: [2,1], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Reflections 4", chapter: 1, moves: 10,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 5, h: 6, walls: [[2,0], [3,2]], hazards: [],
    avatars: [
      { start: [0,0], goal: [4,1], color: "#22d3ee", transform: "mirrorXY" },
      { start: [2,1], goal: [1,4], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Reflections 5", chapter: 1, moves: 10,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[4,1]], hazards: [],
    avatars: [
      { start: [0,3], goal: [4,0], color: "#22d3ee", transform: "mirrorX" },
      { start: [5,4], goal: [0,2], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Reflections 6", chapter: 1, moves: 10,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[5,0], [3,2]], hazards: [],
    avatars: [
      { start: [5,4], goal: [3,0], color: "#22d3ee", transform: "normal" },
      { start: [4,0], goal: [1,0], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Reflections 7", chapter: 1, moves: 11,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[2,4]], hazards: [],
    avatars: [
      { start: [0,2], goal: [5,4], color: "#22d3ee", transform: "mirrorY" },
      { start: [3,0], goal: [2,0], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Reflections 8", chapter: 1, moves: 11,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[1,2], [3,1]], hazards: [],
    avatars: [
      { start: [5,0], goal: [2,3], color: "#22d3ee", transform: "mirrorXY" },
      { start: [0,3], goal: [5,1], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Reflections 9", chapter: 1, moves: 11,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 5, walls: [[1,2], [5,4]], hazards: [],
    avatars: [
      { start: [3,2], goal: [0,4], color: "#22d3ee", transform: "mirrorXY" },
      { start: [3,4], goal: [4,4], color: "#f472b6", transform: "mirrorXY" },
    ],
  },
  {
    name: "Reflections 10", chapter: 1, moves: 12,
    hint: "Mirror twins flip your moves — watch which way each one goes.",
    w: 6, h: 6, walls: [[5,4], [2,3]], hazards: [],
    avatars: [
      { start: [4,5], goal: [4,1], color: "#22d3ee", transform: "mirrorXY" },
      { start: [5,5], goal: [1,4], color: "#f472b6", transform: "mirrorXY" },
    ],
  },
  {
    name: "Blocking Walls 1", chapter: 2, moves: 7,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 7, h: 7, walls: [[1,3], [0,3], [3,4]], hazards: [],
    avatars: [
      { start: [4,1], goal: [2,3], color: "#22d3ee", transform: "mirrorX" },
      { start: [6,2], goal: [3,1], color: "#f472b6", transform: "mirrorXY" },
    ],
  },
  {
    name: "Blocking Walls 2", chapter: 2, moves: 7,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 5, h: 7, walls: [[4,5], [1,6], [0,5], [4,1]], hazards: [],
    avatars: [
      { start: [1,2], goal: [0,1], color: "#22d3ee", transform: "normal" },
      { start: [0,2], goal: [1,4], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Blocking Walls 3", chapter: 2, moves: 7,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 7, h: 5, walls: [[2,3], [0,0], [5,4], [2,0]], hazards: [],
    avatars: [
      { start: [3,0], goal: [6,3], color: "#22d3ee", transform: "mirrorXY" },
      { start: [4,1], goal: [0,2], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Blocking Walls 4", chapter: 2, moves: 8,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 6, h: 5, walls: [[0,0], [3,0], [3,2], [2,2], [4,2], [3,3]], hazards: [],
    avatars: [
      { start: [2,1], goal: [2,0], color: "#22d3ee", transform: "mirrorXY" },
      { start: [2,4], goal: [0,2], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Blocking Walls 5", chapter: 2, moves: 10,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 6, h: 7, walls: [[1,3], [3,0], [2,2], [1,4], [1,6]], hazards: [],
    avatars: [
      { start: [5,1], goal: [1,1], color: "#22d3ee", transform: "mirrorY" },
      { start: [3,1], goal: [3,4], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Blocking Walls 6", chapter: 2, moves: 11,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 7, h: 6, walls: [[6,2], [5,1], [2,4], [6,0], [1,0]], hazards: [],
    avatars: [
      { start: [4,4], goal: [0,1], color: "#22d3ee", transform: "mirrorY" },
      { start: [4,3], goal: [4,1], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Blocking Walls 7", chapter: 2, moves: 12,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 6, h: 7, walls: [[1,0], [4,0], [1,2], [3,0], [2,0]], hazards: [],
    avatars: [
      { start: [5,1], goal: [2,3], color: "#22d3ee", transform: "mirrorX" },
      { start: [5,5], goal: [4,5], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Blocking Walls 8", chapter: 2, moves: 13,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 7, h: 5, walls: [[6,2], [5,2], [2,4], [3,4]], hazards: [],
    avatars: [
      { start: [1,4], goal: [2,3], color: "#22d3ee", transform: "mirrorXY" },
      { start: [3,0], goal: [6,1], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Blocking Walls 9", chapter: 2, moves: 13,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 7, h: 5, walls: [[4,4], [0,0], [3,1]], hazards: [],
    avatars: [
      { start: [3,3], goal: [5,3], color: "#22d3ee", transform: "mirrorX" },
      { start: [0,1], goal: [4,2], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Blocking Walls 10", chapter: 2, moves: 16,
    hint: "Walls stop one twin while the others keep moving. Use them.",
    w: 7, h: 7, walls: [[2,6], [5,1], [6,3], [3,6]], hazards: [],
    avatars: [
      { start: [2,5], goal: [5,0], color: "#22d3ee", transform: "mirrorXY" },
      { start: [2,1], goal: [6,2], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Spikes 1", chapter: 3, moves: 8,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 5, h: 6, walls: [[3,1], [4,2], [2,3]], hazards: [[4,4]],
    avatars: [
      { start: [1,2], goal: [4,0], color: "#22d3ee", transform: "mirrorXY" },
      { start: [2,2], goal: [1,3], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Spikes 2", chapter: 3, moves: 8,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 7, h: 7, walls: [[3,0], [0,2], [6,0]], hazards: [[2,2], [5,5], [2,6]],
    avatars: [
      { start: [1,4], goal: [2,1], color: "#22d3ee", transform: "normal" },
      { start: [0,0], goal: [2,0], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Spikes 3", chapter: 3, moves: 9,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 6, h: 7, walls: [[3,4], [5,4], [3,1]], hazards: [[4,2], [4,0], [1,1]],
    avatars: [
      { start: [3,5], goal: [2,6], color: "#22d3ee", transform: "mirrorX" },
      { start: [5,2], goal: [1,4], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Spikes 4", chapter: 3, moves: 9,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 6, h: 7, walls: [[0,0], [2,3], [0,2]], hazards: [[1,2]],
    avatars: [
      { start: [4,3], goal: [2,2], color: "#22d3ee", transform: "mirrorX" },
      { start: [4,6], goal: [4,4], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Spikes 5", chapter: 3, moves: 9,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 5, h: 7, walls: [[2,1], [0,3], [0,6]], hazards: [[4,1]],
    avatars: [
      { start: [1,3], goal: [3,3], color: "#22d3ee", transform: "mirrorX" },
      { start: [0,2], goal: [3,0], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Spikes 6", chapter: 3, moves: 10,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 6, h: 5, walls: [[1,1]], hazards: [[5,1], [2,3], [2,4], [5,0]],
    avatars: [
      { start: [0,2], goal: [4,0], color: "#22d3ee", transform: "mirrorXY" },
      { start: [4,3], goal: [2,2], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Spikes 7", chapter: 3, moves: 11,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 6, h: 7, walls: [[1,1]], hazards: [[2,5]],
    avatars: [
      { start: [0,6], goal: [1,6], color: "#22d3ee", transform: "normal" },
      { start: [4,3], goal: [5,3], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Spikes 8", chapter: 3, moves: 11,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 5, h: 7, walls: [[2,5]], hazards: [[0,1], [1,5]],
    avatars: [
      { start: [3,1], goal: [2,0], color: "#22d3ee", transform: "mirrorXY" },
      { start: [4,2], goal: [3,4], color: "#f472b6", transform: "mirrorXY" },
    ],
  },
  {
    name: "Spikes 9", chapter: 3, moves: 11,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 5, h: 7, walls: [[1,1], [3,5], [0,3]], hazards: [[0,6], [4,2]],
    avatars: [
      { start: [4,4], goal: [3,4], color: "#22d3ee", transform: "normal" },
      { start: [4,6], goal: [1,2], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Spikes 10", chapter: 3, moves: 11,
    hint: "Spikes reset the level. Route every twin safely around them.",
    w: 5, h: 7, walls: [[4,1]], hazards: [[3,3]],
    avatars: [
      { start: [3,0], goal: [3,1], color: "#22d3ee", transform: "mirrorX" },
      { start: [4,4], goal: [1,6], color: "#f472b6", transform: "mirrorY" },
    ],
  },
  {
    name: "Mastery 1", chapter: 4, moves: 9,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 6, h: 6, walls: [[1,3], [2,3], [1,2]], hazards: [[0,4], [5,3], [0,0]],
    avatars: [
      { start: [4,4], goal: [1,0], color: "#22d3ee", transform: "mirrorY" },
      { start: [2,2], goal: [0,3], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Mastery 2", chapter: 4, moves: 9,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 6, h: 7, walls: [[3,3]], hazards: [[2,3], [5,1], [4,6]],
    avatars: [
      { start: [2,0], goal: [3,0], color: "#22d3ee", transform: "mirrorX" },
      { start: [1,4], goal: [3,1], color: "#f472b6", transform: "normal" },
    ],
  },
  {
    name: "Mastery 3", chapter: 4, moves: 9,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 7, h: 5, walls: [[2,1], [6,1]], hazards: [[1,4]],
    avatars: [
      { start: [4,1], goal: [2,3], color: "#22d3ee", transform: "mirrorX" },
      { start: [3,4], goal: [1,1], color: "#f472b6", transform: "rot90" },
    ],
  },
  {
    name: "Mastery 4", chapter: 4, moves: 11,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 5, h: 6, walls: [[2,2], [4,5], [1,2]], hazards: [[0,5]],
    avatars: [
      { start: [0,0], goal: [3,2], color: "#22d3ee", transform: "mirrorXY" },
      { start: [2,0], goal: [2,1], color: "#f472b6", transform: "normal" },
      { start: [1,4], goal: [4,3], color: "#fbbf24", transform: "mirrorXY" },
    ],
  },
  {
    name: "Mastery 5", chapter: 4, moves: 13,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 7, h: 6, walls: [[3,1], [4,5], [2,4], [4,3]], hazards: [[1,5], [1,4]],
    avatars: [
      { start: [4,1], goal: [5,1], color: "#22d3ee", transform: "mirrorXY" },
      { start: [3,5], goal: [0,0], color: "#f472b6", transform: "mirrorXY" },
    ],
  },
  {
    name: "Mastery 6", chapter: 4, moves: 13,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 7, h: 6, walls: [[5,0], [6,4], [3,4], [6,2]], hazards: [[3,2]],
    avatars: [
      { start: [1,3], goal: [1,4], color: "#22d3ee", transform: "mirrorX" },
      { start: [4,2], goal: [6,3], color: "#f472b6", transform: "mirrorX" },
    ],
  },
  {
    name: "Mastery 7", chapter: 4, moves: 14,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 7, h: 5, walls: [[6,4], [4,3]], hazards: [[0,0]],
    avatars: [
      { start: [5,4], goal: [0,1], color: "#22d3ee", transform: "rot90" },
      { start: [1,2], goal: [4,0], color: "#f472b6", transform: "mirrorY" },
      { start: [3,2], goal: [1,4], color: "#fbbf24", transform: "mirrorX" },
    ],
  },
  {
    name: "Mastery 8", chapter: 4, moves: 16,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 5, h: 7, walls: [[0,5], [4,0], [3,2], [0,0]], hazards: [],
    avatars: [
      { start: [2,4], goal: [1,5], color: "#22d3ee", transform: "mirrorY" },
      { start: [0,4], goal: [4,3], color: "#f472b6", transform: "normal" },
      { start: [2,2], goal: [3,5], color: "#fbbf24", transform: "rot270" },
    ],
  },
  {
    name: "Mastery 9", chapter: 4, moves: 18,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 5, h: 7, walls: [[2,5], [4,3], [1,1]], hazards: [],
    avatars: [
      { start: [4,0], goal: [0,2], color: "#22d3ee", transform: "rot270" },
      { start: [2,1], goal: [1,6], color: "#f472b6", transform: "mirrorXY" },
      { start: [0,5], goal: [3,0], color: "#fbbf24", transform: "mirrorY" },
    ],
  },
  {
    name: "Mastery 10", chapter: 4, moves: 23,
    hint: "Everything at once: mirrors, rotations, walls and spikes.",
    w: 5, h: 7, walls: [[0,2], [0,1]], hazards: [[1,2]],
    avatars: [
      { start: [2,5], goal: [2,1], color: "#22d3ee", transform: "mirrorY" },
      { start: [3,3], goal: [1,6], color: "#f472b6", transform: "rot90" },
      { start: [0,0], goal: [2,3], color: "#fbbf24", transform: "rot270" },
    ],
  },
];

if (typeof module !== "undefined" && module.exports) module.exports = { LEVELS: LEVELS, CHAPTERS: CHAPTERS };
if (typeof window !== "undefined") { window.LEVELS = LEVELS; window.CHAPTERS = CHAPTERS; }
